### ISSUE TITLE
can_delete should be False for inline formsets in CreateWithInlinesView

### ISSUE THREAD

**Issue by palm86** [AndrewIngram/django-extra-views#53] opened 2013-10-18 08:42 UTC
But it should be True for UpdateWithInlinesView. Or am I confused?

**Comment by chidg** [comment] 2015-06-09 06:15
I agree.

**Comment by sdolemelipone** [comment] 2018-11-16 08:56
At first glance I don't see a problem with `can_delete = True` for `CreateWithInlinesView`. If inline formset forms are not attached to an instance, passing in `'DELETE':'on'` does not raise an error.

Can you give an example of the error/complication that arises from `can_delete = True`?

**Comment by chidg** [comment] 2018-11-19 07:51
This is going back a while, but from my perspective the issue is mostly a matter of semantics and aesthetics - if the object is being created, that means it can't be deleted yet, and it's a bit ugly to display a delete checkbox in the form.

**Comment by sdolemelipone** [comment] 2018-11-26 21:51
I agree it is odd to be able to delete forms which aren't yet attached to a model instance. 
There's a couple of things I see against this change:
1. When processing an UpdateWithInlinesView and passing in `extra > 0` to inlineformset_factory, the extra forms will have the checkbox available to delete the blank extra forms, even though they're not associated with a model instance. So it seems inconsistent to force the delete box to be missing for all forms in CreateWithInlinesView, but allowing it to be present for other forms where it is also semantically useless. This suggests to me thatwe should let the user manage the display of the delete box even if `can_delete = True`.
2. For every inline and generic inline FormSetFactory we'd have to do something like:
```
class BaseInlineFormSetFactory(BaseFormSetFactory):
    def get_factory_kwargs(self):
        kwargs = super().get_factory_kwargs()
        if is hasattr(self, 'view'), and isinstance(self.view, CreateWithInlinesView):
            kwargs.setdefault('can_delete', False)
        else:
            kwargs.setdefault('can_delete', True)
        return kwargs
```
which seems pretty ugly.

**Comment by sdolemelipone** [comment] 2019-12-20 14:50
Closing this for now as Django allows forms in formsets which are not associated with an existing model instance to be passed `DELETE = 'on'` in POST data.

**Closed by sdolemelipone** 2019-12-20 14:50 UTC
Labels: Ready to work on
