### ISSUE TITLE
CreateWithInlinesView doesn't save

### ISSUE THREAD

**Issue by heliogutierrez** [AndrewIngram/django-extra-views#71] opened 2014-04-16 18:07 UTC
Hi,

Im doing a proyect with a master-detail form using CreateWithInlinesView for this functionallity,

but it doesn't save, simply the page is reloaded but with the same data in screen, and doesnt commit the transaction. 

When the save button is clicked, nothings happen... any error, any message

Some help will be apreciate please!

***Models.py***
```
class Rekuest(AuditTable):
    TYPEOWNER_CHOICES = (
        ('Empresarial', _(u'Enterprise')),
        ('Particular', _(u'Private'))        
    )
                    
    code                = models.CharField(max_length=50, editable=False)
    bpartner            = models.ForeignKey(BPartner, verbose_name=_(u'Client'))    
    policy_type         = models.ForeignKey(PolicyType)
    type_owner          = models.CharField(_(u'Type Owner'), max_length=15, choices = TYPEOWNER_CHOICES)
    concept             = models.CharField(_(u'Concept'), max_length=60, blank='True')
    orderdate           = models.DateField(_(u'Order Date'))
    status              = models.ForeignKey(Status)
    requestedddate      = models.DateTimeField(_(u'Requested Date'), null=True, blank=True)
    finisheddate        = models.DateTimeField(_(u'Finished Date'), null=True, blank=True)    
    promise_date        = models.DateField(_(u'Promise Date'))    
    email               = models.EmailField(_(u'Email'),null=True,blank=True)
    is_active           = models.BooleanField(_(u'Active'), default=True)
        
    
    def get_next_code(self):
        # Autocalculate next Request code
        if not self.code and self.id:
            num = 1
            try:
                lastcode = Rekuest.objects.exclude(pk=self.id).order_by('-id')[0].code
                parts = lastcode.split('-')
                num = int(parts[1]) + 1
            except:
                pass

            return '%d-%03d' % (self.date.year, num)
        else:
            return self.code
    
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.code = self.get_next_code()
        return AuditTable.save(self, force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

    def __unicode__(self):
        return "[" + str(self.id) + "][" + str(self.orderdate) + "] " + self.bpartner.commercial_name

    class Meta:
        verbose_name = _('Request')
        verbose_name_plural = _('Requests')
    
    
class RekuestDet(AuditTable):
    CURRENCY_CHOICES = (
        ('MXN', _(u'MXN')),
        ('USD', _(u'USD'))        
    )
    
    numrequest          = models.ForeignKey(Rekuest, db_column='Rekuest_id')
    bpartner_vendor     = models.ForeignKey(BPartner, verbose_name=_(u'Insurance'))
    currency            = models.CharField(_(u'Currency'), max_length=15, choices = CURRENCY_CHOICES, default='MXN')
    deductible          = models.DecimalField(_(u'Deductible'), default=0,max_digits=15,decimal_places=2)    
    contact_name        = models.CharField(_(u'Contact Name'),max_length=60)
    phone1              = models.CharField(_(u'Phone'),max_length=60,blank='True')
    paymentterm         = models.ForeignKey(PaymentTerm, null='True')
    description         = models.TextField(_(u'Description'),max_length=200,null='True',blank='True')
    num_cotization      = models.TextField(_(u'Cotization No.'),max_length=20,null='True',blank='True')
    priority            = models.SmallIntegerField(_(u'Priority'),default=0,max_length=2)
    price               = models.DecimalField(_(u'Price'),default=0,max_digits=15,decimal_places=2)
    tax                 = models.DecimalField(_(u'Price'),default=0,max_digits=15,decimal_places=2)
    charges             = models.DecimalField(_(u'Price'),default=0,max_digits=15,decimal_places=2)
    others_charges      = models.DecimalField(_(u'Price'),default=0,max_digits=15,decimal_places=2)
    total               = models.DecimalField(_(u'Price'),default=0,max_digits=15,decimal_places=2)
        
    def get_absolute_url(self):
        return None

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        #self.calculate()
        return AuditTable.save(self, force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

    class Meta:
        verbose_name = _('Request Detail')
        verbose_name_plural = _('Request Detail')
```

***Forms.py***
```
class RekuestForm(forms.ModelForm):

    orderdate = forms.DateField(widget=AdminDateWidget, initial=datetime.date.today, label=_(u'Date'))    
    promise_date = forms.DateField(label=_('Promised Date'), initial=datetime.date.today, required=False)

    class Meta:
        model = Rekuest
        #exclude = ('company',)


class RekuestDetForm(forms.ModelForm):

    price = forms.DecimalField(localize=True, decimal_places=2)
    quantity = forms.IntegerField(localize=True)

    class Meta:
        model = RekuestDet


class RekuestDetInline(InlineFormSet):
    model = RekuestDet
    extra = 1  #extra = Numero de renglones del detalle que mostrara al crear un registro del Master  
    form_class = RekuestDetForm    
```

***Views.py***

```
class RekuestCreateView(NamedFormsetsMixin, CreateWithInlinesView):
    model = Rekuest
    form_class = RekuestForm
    template_name = "op/request_form.html"

    
    inlines = [RekuestDetInline]
    inlines_names = ['RekuestDetInline']

    def get_context_data(self, **kwargs):
        ctx = super(RekuestCreateView, self).get_context_data(**kwargs)
        ctx['title'] = _("Create new Request")
        return ctx

    def get_form(self, form_class): 
        form = CreateWithInlinesView.get_form(self, form_class)
        #Filtra los Socios de Negocio por tipo=Cliente        
        form.fields['bpartner'].queryset = BPartner.objects.filter(iscustomer='True')
        return form

    def construct_inlines(self):
        #Filtra el socio de negocio del detalle por tipo=Proveedor (Aseguradora)
        inlines = CreateWithInlinesView.construct_inlines(self)
        RekuestDetInline = inlines[0]                        
        RekuestDetInline.form.base_fields['bpartner_vendor'].queryset = BPartner.objects.filter(isvendor=True)                    
        return inlines

    def forms_invalid(self, form, inlines):
        messages.error(
            self.request,
            "Your submitted data was not valid - please correct the below errors")
        return super(RekuestCreateView, self).forms_invalid(form, inlines)
    
    def forms_valid(self, form, inlines):
        # Default company
        #self.object.company = self.request.user.company

        # Save object to recalculate totals
        out = CreateWithInlinesView.forms_valid(self, form, inlines)
        self.object.save()
        messages.success(self.request, "Request %s saved." % (self.object.code,))
        return out
```

***request_form.html***
```
<form action="." method="post" id="request_form" class="form-horizontal wysiwyg" enctype="multipart/form-data">
    {% csrf_token %}
	
    <fieldset>
		<div class="well">
	        <legend>
	            Nueva Solicitud
	        </legend>        		
		</div>
        
        <table border="0" cellspacing="5" cellpadding="5">
            <tr>
                <td>{% trans 'Code' %}</td><td><span id="code" class="uneditable-input">{{object.code|default:''}}</span></td>
                <td>{{form.orderdate.label}}</td><td>{{form.orderdate}}</td>
            </tr>
            <tr>
                <td>{{form.bpartner.label}}</td><td>{{form.bpartner}}</td>
                <td>{{form.type_owner.label}}</td><td>{{form.type_owner}}</td>
                <td>{{form.policy_type.label}}</td><td>{{form.policy_type}}</td>
            </tr>
            <tr>
                <td>{{form.concept.label}}</td><td>{{form.concept}}</td>
                <td>{{form.promise_date.label}}</td><td>{{form.promise_date}}</td>
                <td>{{form.status.label}}</td><td>{{form.status}}</td>
            </tr>            
        </table>
        <br/>
        
        <fieldset class="module aligned ">
        <table class="table">
             <tr>
                <th>{% trans 'Insurance' %}</th>
                <th>{% trans 'Agent' %}</th>
                <th>{% trans 'Currency' %}</th>
                <th>{% trans 'Payment Term' %}</th>
                <th>{% trans 'Deductible' %}</th>
                <th>{% trans 'Delete' %}</th>                
             </tr>
             {{ RekuestDetInline.management_form }}
             {% for f in RekuestDetInline %}
                  <tr class="RekuestDetInline" id="id_{{ RekuestDetInline.prefix }}-{{forloop.counter0}}">
                      <td>{{f.id}}                      	  
                          {{f.bpartner_vendor.errors.as_ul}}{{f.bpartner_vendor}}</td>
                      <td>{{f.contact_name.errors.as_ul}}{{f.contact_name|add_class:"input-small"}}</td>
                      <td>{{f.currency.errors.as_ul}}{{f.currency|add_class:"input-small"}}</td>
                      <td>{{f.paymentterm.errors.as_ul}}{{f.paymentterm}}</td>
                      
                      <td class="numberfield field-base"><span>{{f.deductible}}</span></td>
                      <td>{{f.DELETE}}</td>
                  </tr>
             {% endfor %}
        </table>
        </fieldset>

    </fieldset>
    <button class="btn btn-primary btn-large" type="submit">{% trans "Save" %}</button>

</form>
```

**Comment by jonashaag** [comment] 2015-11-30 23:47
Duplicate of #68

**Closed by jonashaag** 2015-11-30 23:47 UTC
